import { Component, ViewChild, AfterViewInit } from '@angular/core';
import { MatTableModule, MatTableDataSource } from '@angular/material/table';
import { MatSortModule, MatSort } from '@angular/material/sort';
import { NgbPopoverModule } from '@ng-bootstrap/ng-bootstrap';

export interface Beer {
  brewery: string;
  name: string;
  abv: number;
  style: string;
  description: string;
}

const EVENT_NAME: string = 'Winter Beer Fest 2025';

const EVENT_URL: string = 'https://www.washingtonbrewersguild.org/winterbeerfest2025/';

const DATA_SOURCE_URL: string = 'https://washingtonbrewersguild-my.sharepoint.com/:x:/g/personal/shawna_washingtonbrewersguild_org/IQADseMm6fE5R54LPyb1VvkSARVZMdC4RQY-Y-qswKjFel0?e=MYDKgS';

const BEER_DATA: Beer[] = [
  { brewery: 'Anacortes Brewery', name: 'Broadsword', abv: 8.3, style: 'Scotch Ale', description: 'Black Patent, Caramel, Chocolate, Munich & Peat smoked malts produce dark color, malty flavor and subtle smokiness in this robust Scottish Ale. Perle, Cascade & Mt Hood provide a balanced bitterness.' },
  { brewery: 'Anacortes Brewery', name: 'Klosterbier', abv: 5.3, style: 'Bavarian Dark Lager', description: 'Smooth, dark lager originally brewed at the Anacortes Brewery under the guidance of the visiting brewmaster of The Kalt Loch Brewery. Inspired by a dark lager brewed for the Engelberg Abbey. Delicately hopped with Perle hops, this beer has become a local favorite.' },
  { brewery: 'Anacortes Brewery', name: 'Noel', abv: 7.0, style: 'Winter Ale', description: 'Brewed to celebrate the holiday season, our winter warmer uses various aromatic specialty malts and has a prominent hop character from mild American Noble varieties.' },
  { brewery: 'Anacortes Brewery', name: 'RCMP', abv: 6.8, style: 'Amber Lager', description: 'Brewed to show our solidarity with our friends to the North, our "Royal Canadian Malted Police Lager" will arrest you with it\'s malty flavor and balanced hop profile.' },
  { brewery: 'Aslan Brewing', name: 'Chai Milk Stout', abv: 4.8, style: 'Milk Stout', description: 'Festive Milk stout notes of Chocolate, coffee paired with warm cinnamon, clove, and cardamom creating a smooth velvety mouthfeel.' },
  { brewery: 'Aslan Brewing', name: 'Dunkel (German Style dark lager)', abv: 5.2, style: 'Dark Lager', description: 'German Dark lager. Notes of chocolate, nuttiness, and cherry with a dry finish.' },
  { brewery: 'Bale Breaker Brewing Company', name: 'High Camp', abv: 7.3, style: 'Winter IPA', description: 'Named for the ski lodge atop our local White Pass Ski Resort, this apres-ski warms from the inside out with aromas of caramel, coffee, citrus, pine and spice. Taking Bale Breaker\'s signature hop-forward style to the dark side with addition of chocolate and rye malts, this balanced IPA is dry-hopped with Mosaic, Simcoe, and experimental hop HBC 630 hops.' },
  { brewery: 'Bale Breaker Brewing Company', name: 'Midnight Snack', abv: 6.0, style: 'Dessert Stout', description: 'Midnight Snack Dessert Stout—because who says you can\'t raid the fridge after dark? Brewed with 2-Row, Munich, Vienna, Flaked Oats, Unmalted Wheat, Midnight Wheat, Chocolate Malt, C-40, and C-120, this stout serves up a rich, layered malt bill that\'s pure temptation. Smooth, decadent, and dangerously drinkable, Midnight Snack is your guilty pleasure in liquid form. Go ahead—sneak one; we won\'t tell.' },
  { brewery: 'Burke-Gilman Brewing Company', name: 'Archangelsk', abv: 15, style: 'Double BBA Russian Imperial Stout', description: 'Russian Imperial Stout aged for 8 months in an Elijah Craig Bourbon barrel, then for 24 months in a Heaven Hills bourbon barrel. Smooth boozy chocolate.' },
  { brewery: 'Burke-Gilman Brewing Company', name: 'Under Every Deep, A Lower Deep Opens', abv: 12.4, style: 'BBA Barleywine', description: 'Complex aroma, with bourbon, brown sugar, caramel, some toffee. Rich caramel, and brown sugar on the palate. Rich maltiness, not too sweet. Aged 18 months in a Willett Bourbon barrel.' },
  { brewery: 'Burke-Gilman Brewing Company', name: 'Castlewood (Bourbon)', abv: 10.8, style: 'BBA English Old Ale', description: 'Dark cherry. Dried prune. Burnt caramel. Aged 12 months in a Woodinville Bourbon barrel' },
  { brewery: 'Distant West', name: 'Uisce Gealach', abv: 7.5, style: 'Warmer', description: 'Distant West\'s version of a winter warmer, Uisce Gealach (Moon Water) has notes of malt, brandy, tobacco, smoke, rye and dried stonefruit. Cleansed with the smoked malt and charged under December\'s cold moon, it will guide you to glory as 2026 approaches.' },
  { brewery: 'Distant West', name: 'Name TBD (something about anniversary and possibly retrievers)', abv: 7, style: 'West Coast IPA', description: 'Distant West teamed up with Dustin and team Hop and Hound to celebrate Dustin\'s upcoming first anniversary owning the renowned taproom and bottle shop in Bothell! Wanting to showcase hops we haven\'t used before, we selected a generous dry hopping of McKenzie hops in addition to Citra and Tettnanger to offer notes of stonefruit, citrus, resin, floral and spice. WA Winter Beer Fest is the FIRST opportunity to try our collaboration before it is formally released for Hop and Hound\'s anniversary.' },
  { brewery: 'Dru Bru', name: 'Bru Ski Patrol', abv: 4.8, style: 'German-Style Dark Lager', description: 'An award-winning German-style "Dunkel" lager. German-grown malted barley produces flavors of toast, chocolate, and hazelnut. A dose of German-grown hops provides herbal and spicy notes. Brewed for our love of snow rescue and ski patrollers, it\'s the beer to pick up when the snow\'s coming down.' },
  { brewery: 'Dru Bru', name: 'Kölsch', abv: 5.0, style: 'German-Style Golden Ale', description: 'An award-winning German-style golden ale. German-grown pilsner and wheat malts give it a nice bready aroma, subtle honey flavor, and provide for a delicate but complex finish. It\'s crisp and refreshing, not hoppy.' },
  { brewery: 'Dru Bru', name: 'Anniversary Ale', abv: 6.8, style: 'German-Style Sticke Alt', description: 'In celebration of our 10th anniversary, we proudly present this dark, bold ale. Featuring rich malt flavors of caramel, chocolate, and coffee, and balanced by a piney, bitter edge, making it perfect to toast to a decade of Dru Bru!' },
  { brewery: 'Fast Fashion', name: 'Universal Appeal', abv: 5.2, style: 'German Pils', description: 'German Pils with Mittelfrüh, Tettnang, and Spalter Select.' },
  { brewery: 'Fast Fashion', name: 'Curtain Call', abv: 6.7, style: 'Red Ale', description: 'Hoppy Red Ale brewed with freshly kilned whole cone Segal Ranch Centennial. Collab with Monkish.' },
  { brewery: 'Flying Bike Cooperative Brewery', name: 'Gingerbread Sleigher Vienna Lager', abv: 5.5, style: 'Vienna Lager', description: '' },
  { brewery: 'Flying Bike Cooperative Brewery', name: 'Solstice Pomegranate Peach Sour', abv: 6.2, style: 'Sour', description: '' },
  { brewery: 'Fremont Brewing', name: '2025 BBOMB', abv: 14, style: 'Barrel Aged Imperial Winter Ale', description: '' },
  { brewery: 'Fremont Brewing', name: 'Extra Lush', abv: 9, style: 'Triple IPA', description: 'Extra Lush is triple the tropical treat from the Pacific Northwest. Brewed with three times the amount of hand-selected malts and tropical hops. Live the Extra Lush Life!' },
  { brewery: 'Fremont Brewing', name: '2021 Rusty Nail', abv: 14.2, style: 'Barrel Aged Imperial Oatmeal Stout', description: 'The Rusty Nail begins life as The First Nail, an oatmeal stout of epic proportions with brewer\'s licorice, smoked barley, and pale malt and is then aged on cinnamon bark. She becomes The Rusty Nail after spending 15 months in 12-year old bourbon barrels.' },
  { brewery: 'Fremont Brewing', name: 'Lost Lake Dry Cider', abv: 6.5, style: 'Dry Cider', description: 'AROMA: Apple, stone fruit with some white grape, florals, white wine & green Jolly Rancher. FLAVOR: Light sweetness, moderately tart with no bitterness.' },
  { brewery: 'Garden Path Fermentation', name: 'The Little Horse Around.', abv: 4.5, style: 'Hoppy Table Beer', description: 'Table beer first fermented with our house culture before heading to puncheon where it was inoculated with a house Brett culture grown back up from bottle dregs from one of our older native yeast beers. Hopped initially with PNW Saaz and Tettnang. It was in puncheon for about three or four months before dry hopping (whole leaf Saaz, Cascade, Hop Skagit grown Mount Rainier and Hop Skagit grown Nugget) and package-conditioned with local honey another two months. Earthy on the nose, calling to mind damp leaves and straw. Balanced and pleasant herbal bitterness that finishes floral with hints of ripe pineapple and cantaloupe rind. Bone dry and incredibly drinkable!' },
  { brewery: 'Garden Path Fermentation', name: 'The Golden Age.', abv: 6.3, style: 'Native Yeast Saison', description: 'Four grain native yeast saison dry-hopped with El Dorado. Smooth and balanced with a biscuity malt backbone, subtle fruit notes, and a crisp, gently warming finish.' },
  { brewery: 'Garden Path Fermentation', name: '(This is A) Crush Story.', abv: 6.66, style: 'Beer Piquette', description: 'Garden Path Co-Creator, Amber Watts, has had a crush on the band Too Much Joy since she was in high school, and there was no way she was going to pass up the opportunity to make a beer with them. In the spirit of collaboration–lead singer Tim Quirk\'s love of crushable lagers, and our love of crushing things during harvest season–we added spent Pinot Noir pomace to a batch of native-yeast table beer, let those guys hang out for a while, and then added whole cherries to round out the base. In every possible sense, this beer is a Crush Story.' },
  { brewery: 'Garden Path Fermentation', name: 'The Spontaneous Ferment: 5-Year Blend on Raspberries & Blue Haskap.', abv: 6.8, style: 'Spontaneous Ale', description: 'We brewed our very first batch of spontaneously fermented beer at Garden Path on May 1, 2018, just weeks after we opened our doors. From literally the very beginning, spontaneous fermentation–filling our coolship with hot wort on a chilly night, capturing airborne yeast, and letting the beer slowly ferment in oak–has been one of the projects we\'re most passionate about. We\'ve released two three-year spontaneous blends, inspired by some of our favorite Belgian gueuzes, and this beer, blended in honor of our fifth anniversary, is an even deeper cut. It contains spontaneously fermented beers from five seasons, beginning in 2018. In June of 2024, we added 200 pounds of raspberries and 84 pounds of blue haskap berries (also known as honey berries) grown at Beaver Marsh Blueberry Farm (formerly Lenning Farms) in Mount Vernon, Washington, which refermented for several months, before being moved off the fruit and eventually packaged in January 2025. This robust beer is a purple-red color, with a punch of fresh fruit and soft minerality on the nose, and assertive fruit and bright but gentle acid on the finish.' },
  { brewery: 'Georgetown Brewing Company', name: 'Barrel Aged 18lb Porter', abv: 9.7, style: 'Barrel Aged Porter', description: 'This imperial version of our 9lb Porter was aged for nearly a year in bourbon barrels. The vanilla and bourbon notes from barrel-aging intensifies the plush, roasted, and aromatic chocolate notes, making this a winter sipper sure to please.' },
  { brewery: 'Georgetown Brewing Company', name: 'Pirate Captain Dark Lager', abv: 6, style: 'Dark Lager', description: 'A robust lager, rich with chocolate aromas and roasted flavors. This lager starts smooth and light, yet finishes with a velvety mouthfeel enjoyed by working captains and partying pirates alike.' },
  { brewery: 'Georgetown Brewing Company', name: 'Sky of Life Golden Ale w/Tangerine', abv: 6.6, style: 'Golden Ale', description: 'A new sour from brewer Craig, this ale is giving mango and pineapple on the tropical front, and a bright sweet citrusy pop thanks to the tangerine addition. The varied malt bill contributes to a soft mouthfeel and complex notes courtesy of the rye (lingering spice), wheat (soft & pillowy), spelt (grapenut), and light Munich (fresh sweet rolls). Contains wheat.' },
  { brewery: 'Ghostfish Brewing', name: 'Little Redhead', abv: 6.6, style: 'Chocolate Raspberry Stout', description: 'Adjunct filled stout, heaps of cacao nibs, raspberry puree, and a touch of oak.' },
  { brewery: 'Ghostfish Brewing', name: 'Stocking Stuffer', abv: 5.7, style: 'Holiday Ale', description: 'Festive holiday ale, incorporating spices including coriander, juniper, and ginger.' },
  { brewery: 'Ghostfish Brewing', name: 'Peak Buster', abv: 8.0, style: 'Double IPA', description: 'Big Northwest hops, notes of citrus and pine, balanced malt finish.' },
  { brewery: 'Here Today Brewery & Kitchen', name: 'Sharpie Mustache', abv: 10, style: 'Imperial Brown Ale', description: 'Imperial Brown Ale aged in Maker\'s Mark barrels that were conditioned with the ingredients for the Sharpie Mustache Cocktail. Very Amaro-forward' },
  { brewery: 'Here Today Brewery & Kitchen', name: 'Double R', abv: 5.8, style: 'Breakfast Stout', description: 'Breakfast Stout brewed as an Irish Export Stout, conditioned on Olympa Morning Sun coffee and Maple Syrup.' },
  { brewery: 'Here Today Brewery & Kitchen', name: 'Hyperstep', abv: 6.7, style: 'West Coast IPA', description: 'with Citra, Amarillo, Nelson Sauvin, El Dorado.' },
  { brewery: 'Icicle Brewing Company', name: 'Nitro Peppermint Mocha', abv: 10.5, style: 'Imperial Pastry Stout', description: 'A one-off release exclusively for Winter Beer Fest, this is the only keg in existence! Made with Cafe Mela\'s Brazil French Roast coffee, this imperial stout is a decadent taste of the holidays in a glass! Rich, creamy, and pepperminty! (Will only be available half of each session - alternating with the Nitro Caramel Macchiato Stout)' },
  { brewery: 'Icicle Brewing Company', name: 'Nitro Darker Persuasion Caramel Macchiato Stout', abv: 9, style: 'Pastry Stout', description: 'A special nitro version of our limited release imperial pastry stout! This scrumptious brew is carefully crafted to evoke the decadent flavors of a classic espresso delight. Enjoy flavors of rich caramel, locally roasted coffee, and notes of creamy vanilla in a smooth, well-balanced and nuanced treat. Contains lactose. (Will only be available half of each session - alternating with the Peppermint Mocha Stout)' },
  { brewery: 'Icicle Brewing Company', name: 'Whispers In the Nebula Imperial Stout', abv: 9.5, style: 'Imperial American Stout', description: 'Brewed on our small-batch system in our taproom, this quintessential imperial stout is rich, dark, and roasty, with notes of coffee and chocolate. Wade through the dark expanse of the universe with this strong and full-bodied delight!' },
  { brewery: 'Icicle Brewing Company', name: '2024 Barrel-Aged Darkest Persuasion Imperial Stout', abv: 11, style: 'Imperial Pastry Stout', description: 'We\'ve saved this vintage specifically for Winter Beer Fest! Conditioned on Ugandan vanilla beans, Ecuadorian and Gahanian cacao nibs, toasted coconut and blended from Dry Fly Wheat Whiskey and Triticale Whiskey barrels. Expect a smooth, nuanced, and balanced blend of creamy chocolate, vanilla and coconut.' },
  { brewery: 'Icicle Brewing Company', name: 'Enchantments Hazy IPA No. 24', abv: 6.9, style: 'Hazy IPA', description: 'The 24th entry in our award-winning hazy IPA series features ample amounts of Eclipse, Galaxy, Citra, and Mosaic hops, delivering notes and aromas of stone fruit, juicy citrus and tropical fruit medleys.' },
  { brewery: 'Ilk Beer', name: 'Remember the Porter', abv: 4.6, style: 'English Porter', description: 'We finally made a porter! And true to fashion, this is not a big modern American porter but instead, a smaller more reserved English take on the style.' },
  { brewery: 'Ilk Beer', name: 'Spare Time in Bodega Bay', abv: 6.8, style: 'Red Celebratory IPA', description: 'Our nod to the classic celebratory red IPA! Fresh kiln Dolcita and Citra hops meets a satisfyingly malty but still crusher tank on the style!' },
  { brewery: 'Ilk Beer', name: 'Tottens Best Bitter', abv: 3.8, style: 'Cask Best Bitter', description: 'Named for one of Olympias many inlets and relatively unknown midshipman George Totten, Tottens Best bitter is the beer we imagine this Englishman, far far from home, would have wanted to enjoy upon his return home.' },
  { brewery: 'Jötunn Ciderhouse', name: 'Snowdazzle Citrus', abv: 6.4, style: 'Mostly Dry Cider', description: 'Sunshine bursts triumphantly through a wintry blizzard, scattering sparkling snow and dazzling every sense in its path. Bright, victorious citrus leads the way, while winter spices sing in warm celebration. Crisp orange, slight cinnamon sweetness, and just a touch of tea smugness. It\'s the taste of winter conquered by pure, sparkling joy.' },
  { brewery: 'Jötunn Ciderhouse', name: 'Pretty Berry', abv: 6.6, style: 'Mostly Dry Cider', description: 'Like a French rosé that\'s trying so hard to be elegant but mostly just ends up embarrassing itself. Kind of like that friend that talks fancy words but can\'t quite pull them off. Tart cranberry and bold florals are there to help, but those dry tannins? They\'re just too sharp to keep quiet. It\'s pretty, it\'s awkward, and way too real for the classic fairy tale ending.' },
  { brewery: 'Jötunn Ciderhouse', name: 'Night Market', abv: 6.7, style: 'Very Dry Cider', description: 'Step into the Night Market, where hanging lanterns flicker, and the winter air is rich with spice. Cinnamon, ginger and cardamom beckon, vanilla whispers a fortune of whipped-cream, and toasted yerba mate lurks beneath the surface. Every sip feels like floating through moonlit stalls on a magic carpet, equal parts mystery and mischief, as you fall under its spell.' },
  { brewery: 'Kulshan Brewing Co.', name: 'Royal Tannenbaum', abv: 8.6, style: 'Holiday Ale', description: 'Ripe with festive spirit, Royal Tannenbaum is balanced and clean, with just enough spice and warming alcohol notes to keep you warm on these cold, dark days. This year\'s Tannenbaum boasts alluring notes of fir, spruce, and pithy citrus, followed by resinous and slightly lingering hop bitterness. A treat we get to experience but once a year, Royal Tannenbaum is not for the faint of heart, but warmly rewards those who dare enter its realm.' },
  { brewery: 'Kulshan Brewing Co.', name: 'Barrel Aged Kitten Mittens', abv: 12, style: 'Barrel Aged Winter Ale', description: 'This year\'s Barrel Aged Kitten Mittens is smooth, complex and warming. Big notes of Chocolate, cherry and dark stone fruit dominate in both the flavor and aroma, along with accents of toffee, whiskey and vanilla. This vintage is a blend of barrels from Stein Distillery in Joseph, Oregon.' },
  { brewery: 'Kulshan Brewing Co.', name: 'Cran You Kick It?', abv: 4.3, style: 'Holiday Kettle Sour', description: 'Delightfully tart and refreshing sour ale, brewed with sweet orange peel and fermented with cranberry puree.' },
  { brewery: 'Ladd & Lass Brewing', name: 'Deprived of Light', abv: 0, style: 'Russian Imperial Stout', description: '' },
  { brewery: 'Ladd & Lass Brewing', name: 'Pyramid of Haze', abv: 0, style: 'Hazy IPA', description: '' },
  { brewery: 'Ladd & Lass Brewing', name: '(FRI) Brewer\'s Choice', abv: 0, style: 'SURPRISE!!', description: '???' },
  { brewery: 'Ladd & Lass Brewing', name: '(SAT) Barrel-aged Year 2 (2024)', abv: 0, style: 'English Barleywine', description: '' },
  { brewery: 'Matchless Brewing', name: 'Beermosa', abv: 6.8, style: 'Hazy IPA', description: 'Citra, Motueka & Nelson Sauvin hops.' },
  { brewery: 'Matchless Brewing', name: 'Winterberry Sour', abv: 5.7, style: 'Kettle Sour', description: 'This tart ale was made with a blend of berries featuring cranberries in the forefront and a compliment of select citrus to tie it all together. Rosy and inviting in appearance with tart notes of stone fruit, berries and a subtle citrus tang. This ale is perfect for the season ahead. Cheers!' },
  { brewery: 'Matchless Brewing', name: 'Cold Chocolate', abv: 8, style: 'Imperial Stout', description: 'There is snow in the mountains. There is a nip in the air. You can see your breath as it mingles with the frosty wind. And that means it\'s time to curl up by a roaring fire with a nice mug of Cold Chocolate? Why risk burning your tongue & fingers? We\'ve got all the rich chocolate & creamy vanilla flavors you need in a cool 16 oz can. It will warm you up from the inside out.' },
  { brewery: 'Metier Brewing Company', name: 'Central Calling IPA', abv: 6.5, style: 'IPA', description: 'A simple grain bill of 2-row and Pilsner malt allows Mosaic and Strata hops to pop in this crisp golden ale. Grapefruit and Tropical fruit flavors backed up with moderate bitterness. Enjoy this refreshing West Coast IPA.' },
  { brewery: 'Metier Brewing Company', name: 'Schwarzbier', abv: 5.4, style: 'Dark Lager', description: 'German for Black Beer, this dark lager showcases chocolate aromas and flavors with a mild roastiness. Medium bodied with a clean finish.' },
  { brewery: 'Old Stove Brewing Company', name: 'Quiet Eon 2025', abv: 0, style: 'Bourbon Barrel Aged Stout', description: 'Imperial Stout aged in Bourbon Barrels' },
  { brewery: 'Old Stove Brewing Company', name: 'Polar-Rye\'zd Winter IPA - Holiday Edition', abv: 7.5, style: 'Winter IPA', description: 'Winter IPA spiked with special Holiday spices' },
  { brewery: 'Peace of Mind Brewing', name: 'Xenowort', abv: 7, style: 'CDA', description: 'Brewed with Amarillo hops for a subtle citrus lift and finished with a late addition of black malt for that signature midnight hue without the roast bite.' },
  { brewery: 'Peace of Mind Brewing', name: 'Nakatomi Porter', abv: 5.5, style: 'American Porter', description: 'Rich chocolate, toasted malt, and smooth roast come together in this American porter brewed with Maris Otter, Victory, and a touch of Crystal 60. Northern Brewer hops give it a clean bitterness, while a Cashmere whirlpool adds a subtle hint of citrus. Dark, bold, and surprisingly crisp yippee ki-yay, beer lovers.' },
  { brewery: 'Peace of Mind Brewing', name: 'Dang it, Bobby!', abv: 5, style: 'Blonde Ale', description: 'Crisp and refreshing with a soft malt backbone from 2-Row and Vienna, plus a touch of Carapils for body. Lightly bittered with Magnum and finished in the whirlpool with Mandarina Bavaria, giving a smooth pop of tangerine and citrus zest.' },
  { brewery: 'Postdoc Brewing Company', name: 'Falling Spikey Pods', abv: 5.2, style: 'Chestnut Brown Ale', description: 'Roasted Chestnuts, Bread Crust, Caramel, Toasty **CONTAINS NUTS**' },
  { brewery: 'Postdoc Brewing Company', name: 'Cosmic Dust Analyzer', abv: 5.9, style: 'CDA', description: 'Grapefruit, Stone fruit, Whisper of Chocolate' },
  { brewery: 'Postdoc Brewing Company', name: 'L.A.B. Partner w/ Cranberry', abv: 4.6, style: 'Fruited Gose', description: 'Dry Cranberry, Tart, Sourdough' },
  { brewery: 'Postdoc Brewing Company', name: '2024 BBA Demon Star Cinnamon', abv: 10.7, style: 'Barrel-aged Imperial Stout', description: 'Cinnamon, Vanilla, Chocolate, Bourbon' },
  { brewery: 'Postdoc Brewing Company', name: '2025 BBA Demon Star Blueberry', abv: 11.5, style: 'Barrel-aged Imperial Stout', description: 'Blueberry, Espresso, Dark Chocolate, Bourbon' },
  { brewery: 'Remlinger Brewery', name: 'a Gose', abv: 5, style: 'Gose', description: '' },
  { brewery: 'Remlinger Brewery', name: 'a Barley Wine', abv: 9.7, style: 'Barley Wine', description: '' },
  { brewery: 'Remlinger Brewery', name: 'a Tropical Black Pear Cider', abv: 6.8, style: 'Cider', description: '' },
  { brewery: 'Republic of Cider', name: 'George\'s Washington Cider', abv: 6.4, style: 'Belgian inspired Dry Cider', description: '' },
  { brewery: 'Republic of Cider', name: 'Plum Bubbly', abv: 6.4, style: 'Dry tart plum Cider', description: '' },
  { brewery: 'Republic of Cider', name: 'More Cowbell', abv: 6.9, style: 'Farmhouse pet-nat Cider', description: '' },
  { brewery: 'Republic of Cider', name: 'Roasted Hatch Chile', abv: 6.8, style: 'Cider', description: 'Fresh roasted hatch chilies cold soaked in cider, finished w/ agave.' },
  { brewery: 'Republic of Cider', name: 'Mr. Lee\'s Formosa Fizz', abv: 0, style: 'Non-Alcoholic', description: '' },
  { brewery: 'Reuben\'s Brews', name: 'Festive Ale', abv: 7.5, style: 'Winter Warmer', description: 'Brewed to invoke a Chocolate Orange Candy. This Winter Warmer is brewed with toasted rye, cocoa nibs and Orange Zest and pairs well with Festive Winter activities.' },
  { brewery: 'Reuben\'s Brews', name: 'Julebok', abv: 7, style: 'Nordic Holiday Beer', description: 'Given our neighborhood\'s Nordic heritage, we thought It would be fun to brew a holiday beer that leaned Into Scandinavian traditions. Taking Inspiration from the Christmas bread that Ballard bakeries sell this time of year, we brewed a strong, malty lager accented with cardamom and fermented with a Norwegian Kviek yeast for a touch of fruity character. Floral and fruity on the nose, Julebokk combines notes of baking spice with a pleasant level of balancing bitterness on the palate.' },
  { brewery: 'Reuben\'s Brews', name: '2020 Vintage BBIS', abv: 14, style: 'Bourbon Barrel Imperial Stout', description: 'The majority of the barrels in this year\'s blend have been aging for about one year, and the addition of some two year-aged BBIS into the blend adds layers of complexity. We barrel age this stout in a blend of 10 to 12 year bourbon barrels. Using the same oat-forward and British specialty malt recipe that hails back from the original version brewed in 2013, we introduced some new techniques to make the beer bigger, richer and silkier.' },
  { brewery: 'Reuben\'s Brews', name: 'Pecan Pie Three Ryes Men Barrel Aged Barley Wine', abv: 13.7, style: 'Barrel Aged Barley Wine', description: 'A barrel-aged barleywine brewed with three kinds of rye malt with additions of roasted pecans and vanilla bean. This homage to a classic American pie amps up the notes of caramel and chocolate of our GABF-winning Three Ryes Men.' },
  { brewery: 'Reuben\'s Brews', name: 'Party On NA IPA', abv: 0, style: 'NA IPA', description: 'Brewed with a pair of dynamic hop varieties for notes of citrus, pine, and tropical fruit, this India Pale Ale is the drink to reach for when you want something bold and bright without the alcohol.' },
  { brewery: 'Reuben\'s Brews', name: 'Party On NA Gold', abv: 0, style: 'NA Gold', description: '' },
  { brewery: 'Rooftop Brewing Co', name: 'Jolly Roger Holiday Ale', abv: 9.5, style: 'Winter Beer', description: 'English Strong Ale in style combining rich malt flavors with NW Chinook, Cascade, and Amarillo hops. Jolly Roger is flavorful but smooth. Taste the legend that Northwesterners have come to identify with the most wonderful time of the year.' },
  { brewery: 'Rooftop Brewing Co', name: 'Scotch Scotch Scotchity Scotch Ale', abv: 8.0, style: 'Peated Scotch Ale', description: 'Our Scotch Scotch Scotchity Scotch Ale is brewed with real peat-smoked Scottish malt, so just like and Islay scotch, it has a hearty smoked peat flavor and aroma. As we like to say around the brewery: more peat, less sweet.' },
  { brewery: 'Single Hill Brewing Company', name: 'Duplicator', abv: 7.6, style: 'Doppelbock', description: 'Deep amber lager featuring intense malt character of toffee and toasted nuts. Perfect for warming yourself in the winter chill.' },
  { brewery: 'Single Hill Brewing Company', name: 'Truth Watcher', abv: 5.3, style: 'West Coast Pils', description: 'Featuring a hop duo of the classic Centennial and the modern Strata, this West Coast Pils is pale and easy on the palate, with notes of grapefruit, berries, and pine.' },
  { brewery: 'Single Hill Brewing Company', name: 'Overstory', abv: 12.3, style: 'Barrel-Aged Imperial Stout', description: 'This barrel-aged beer pulls from a blend of barrels to present flavors of rich oak and spice atop the full-bodied roast and cocoa notes of the base Imperial Stout.' },
  { brewery: 'Snoqualmie Falls Brewery', name: 'Steam Train Porter', abv: 5.0, style: 'American Porter', description: 'This lip-smacking dark ale is mellow and malty. The aroma is reminiscent of bittersweet dark chocolate and the caramel and roast malt flavors are exceptionally smooth. Medium bodied, with a slightly sweet edge but a dry finish.' },
  { brewery: 'Snoqualmie Falls Brewery', name: 'Axe Men', abv: 7.5, style: 'Red Ale', description: 'This robust red ale, brewed with lots of Munich malt, has a lovely red color, super-silky body, and is toasty, rich and malty. We used Cascade hops for a pleasant citrus aroma and flavor. It finishes on the dry side, yet with a slight sweetness on the palate.' },
  { brewery: 'Stoup Brewing', name: 'Powder Tracks', abv: 8.2, style: 'Winter Ale', description: 'Powder Tracks Winter Ale, a malt forward beer with chocolate and caramel notes touched with a hint of citrus aroma, will call you to forget the noise and embrace the quiet of a winter trail.' },
  { brewery: 'Stoup Brewing', name: 'Schwarzbier', abv: 4.8, style: 'Schwarzbier', description: 'A moderately dry lager with a mouthwatering roastiness. It\'s the perfect hybrid of malt flavor and lager crispness.' },
  { brewery: 'Stoup Brewing', name: 'Chrome Posies Double Hazy IPA', abv: 8.0, style: 'Double Hazy IPA', description: 'A big, bold fruit-forward IPA. Idaho 7, Citra and Riwaka hops create layers of tropical and citrus aromas and flavors.' },
  { brewery: 'Structures Brewing', name: 'Doppelbock', abv: 8.1, style: 'Lager', description: 'Dark lager with notes of malt forward breadiness, molasses and toasted toffee with a rich balanced full bodied mouthfeel, dark fruits highlighted with plum esters.' },
  { brewery: 'Structures Brewing', name: 'Julbock', abv: 7.4, style: 'Bock', description: 'A winter Bock brewed at a higher gravity for the colder months. Malt-rich flavors of toffee, dried fruits and dark chocolate. Lagered for 8 weeks for a smooth round finish.' },
  { brewery: 'Structures Brewing', name: 'Seeing Things', abv: 8.3, style: 'Double IPA', description: 'Hazy Double IPA brewed with a massive amount of oats, double dry hopped with Nelson and Citra. Notes of passionfruit, bright gooseberry papaya, and diesel.' },
  { brewery: 'Structures Brewing', name: 'Thank you for 7 years', abv: 11.6, style: 'BBA Imperial Stout - Barleywine blend', description: 'A Blend of Imperial Stout and Barleywine. 65% stainless, 35% Bourbon barrel aged. Conditioned on coffee from Steed Roasters and a hint of toasted Coconut.' },
  { brewery: 'Terramar Brewstillery', name: 'Rain Shadow Stout', abv: 6.0, style: 'American Stout', description: 'Smooth, full bodied stout with notes of bittersweet chocolate, freshly roasted coffee, and dark toffee.' },
  { brewery: 'Terramar Brewstillery', name: 'Frigid Zest Cold IPA', abv: 6.8, style: 'Cold IPA', description: 'Crisp and dry cold IPA featuring notes of tropical stone fruit, tangerine, pineapple, and grapefruit, with a slightly dank/piney finish.' },
  { brewery: 'Terramar Brewstillery', name: 'Raspberry Blueberry Harvest Cider', abv: 6.9, style: 'Fruited Cider', description: 'Cosmic Crisp apples fermented on an English Ale yeast strain and then conditioned on loads of locally grown blueberries and raspberries.' },
  { brewery: 'Triplehorn Brewing', name: 'Stupid Monk-E', abv: 9, style: 'Belgian Ale', description: 'Brewed with orange peel, coriander, and fresh honey. You\'ll taste a spicy and fruity ale with notes of clove, citrus, and honey.' },
  { brewery: 'Triplehorn Brewing', name: 'Raise Your Horns Ryebock Lager', abv: 7.3, style: 'Ryebock Lager', description: 'Our winter take on a classic German summer lager made with Thomas Fawcett rye malt. Fruity, spicy, bright, and clean to finish.' },
  { brewery: 'Triplehorn Brewing', name: 'Wicked Pissah NE IPA', abv: 6.7, style: 'NE IPA', description: 'East Coast Hazy IPA made with citra and amarillo hops, boasting bold, citrus notes' },
  { brewery: 'Varietal Beer Co', name: 'Mirror Shades', abv: 6.7, style: 'IPA', description: 'A cyberpunk take on a classic WC IPA. Citra, Mosaic, Simcoe and Chinook run through rainy city streets illuminated by buzzing neon, pulsating electronic dub rhythms pound from behind glass and steel doors. You find this beverage has interfaced with your bionically enhanced neural net, data constellations flowering in your mind with hyper technologically extracted hop oils coursing through your sub-matrix. This beer is smelling like it tastes as your memory is downloaded into the mainframe and exported to memories of piney woods, citrus groves and time when you and the world were simpler.' },
  { brewery: 'Varietal Beer Co', name: 'Chocolate Cherry Stout', abv: 5.8, style: 'Stout', description: 'A beer based on our favorite locally produced chocolate covered cherry candy. Made with local cherries sourced in the PNW we brewed a rich dark, chocolatey stout based and blended in the sweet cherries. A treat for you and yours this holiday season!' },
  { brewery: 'Walking Man Brewing', name: 'Cherry Stout', abv: 7.2, style: 'Stout', description: 'Brewed with 7 grains including flaked oats, this complex brew offers big, chocolate, coffee flavors that mesh beautifully with sweet, rich cherries in this unique twist on our classic Oatmeal Stout.' },
  { brewery: 'Walking Man Brewing', name: 'Old Stumblefoot \'24', abv: 10.1, style: 'Barleywine', description: 'In celebration of our 24th anniversary, we dug into the archives and brewed our classic Barleywine-style ale. A year of conditioning in keg adds new dimensions to this pub legend!' },
  { brewery: 'Yonder Cider', name: 'Wassail Spiced', abv: 6.9, style: 'Spiced Cider', description: 'This winter warmer cider is full of spice, flavor and tradition. Made with a blend of juicy culinary apples and tannic, Frequin Rouge. We then steep the cider with all the flavors of the season.' },
  { brewery: 'Yonder Cider', name: 'Velvet Cashmere', abv: 8.9, style: 'Amaro Cider', description: 'We\'ve taken our Negroni-inspired winter seasonal - Cashmere - and blended it with Fast Penny Spirits\' Americano amaro for a cider unlike any other.' },
];

@Component({
  selector: 'app-beer-table',
  imports: [MatTableModule, MatSortModule, NgbPopoverModule],
  templateUrl: './beer-table.component.html',
  styleUrl: './beer-table.component.scss',
})
export class BeerTableComponent implements AfterViewInit {
  event_name = EVENT_NAME;
  event_url = EVENT_URL;
  data_source_url = DATA_SOURCE_URL;
  displayedColumns: string[] = ['brewery', 'name', 'abv', 'style'];
  dataSource = new MatTableDataSource(BEER_DATA);

  @ViewChild(MatSort) sort!: MatSort;

  ngAfterViewInit() {
    this.dataSource.sort = this.sort;
  }
}
